Contact page
BuildForSDGCohort2/team-086-group-a-frontend pull request #12
Opened 2020-09-13 22:42 UTC by SenJames

The contact page has just being completed and ready for review.

The route is /team-086-group-a-frontend/contact

Images below:
![image](https://user-images.githubusercontent.com/35000589/93030389-a3729700-f61a-11ea-9762-7d22c3d0ef37.png)

![image](https://user-images.githubusercontent.com/35000589/93030396-b38a7680-f61a-11ea-9846-7067ddd55f8c.png)

2020-09-14 10:40 UTC, chibuike07 requested changes
the styles try and look into it, 

1. In contact.jsx, your state value should be added in the nonregistered context in the context folder
2. In the contact form, the placeholder does not appear on page load rather when the value has been added and deleted
3.  seems you prefer using APIs, why not try and do it from scratch. 
4.  In the buttons you used, A button component has been already set for everybody.
5.  The google map shows on load and immediately throws an error. check your console,
6. check the contact.jsx line 149 where you used disable it throwing an error to the console, 
7. CSS style should the defined in the style folder not any other place
8. In the unprotected routes your component paths seem not to be correct
9. again seems that the bootstrap css you added is affecting the other components css please try and check it out

2020-09-18 05:01 UTC, HENRYKC24 reviewed
@SenJames I really could not see the page when i routed to team-086-group-a-frontend/contact
![Screenshot from 2020-09-18 06-00-49](https://user-images.githubusercontent.com/45668340/93557981-56712680-f974-11ea-941c-09798667c00c.png)

2020-09-18 10:36 UTC, SenJames commented
> the styles try and look into it,
> 
> 1. In contact.jsx, your state value should be added in the nonregistered context in the context folder
> 2. In the contact form, the placeholder does not appear on page load rather when the value has been added and deleted
> 3. seems you prefer using APIs, why not try and do it from scratch.
> 4. In the buttons you used, A button component has been already set for everybody.
> 5. The google map shows on load and immediately throws an error. check your console,
> 6. check the contact.jsx line 149 where you used disable it throwing an error to the console,
> 7. CSS style should the defined in the style folder not any other place
> 8. In the unprotected routes your component paths seem not to be correct
> 9. again seems that the bootstrap css you added is affecting the other components css please try and check it out

Hello TTL. 

Thanks for the review....

I have made the required changes except the suggestion to use API and they seem to be working now. 

Perhaps the API usage is one of choice of style. Anyway I am willing to learn. 


Kindly help review.

2020-09-18 10:37 UTC, SenJames commented
> @SenJames I really could not see the page when i routed to team-086-group-a-frontend/contact
> ![Screenshot from 2020-09-18 06-00-49](https://user-images.githubusercontent.com/45668340/93557981-56712680-f974-11ea-941c-09798667c00c.png)

Hi KC, 

You need to switch to the contact page branch to be able see the changes

Thanks.

2020-09-18 15:02 UTC, chibuike07 reviewed
The footer component is affected by your styles. Try as much as possible not to be passing props, we already have the context that gives us a unidirectional flow of the state.

2020-09-18 15:02 UTC, chibuike07 commented on src/Pages/ContactPage/contact.jsx
> +        this.state = {
The state should be declared inside the nonregistrationcontext

2020-09-18 15:02 UTC, chibuike07 commented on src/Pages/ContactPage/contact.jsx
> +    handleChange = (e) => {
Adjust the handle change function

2020-09-18 15:02 UTC, chibuike07 commented on src/Pages/ContactPage/contact.jsx
> +    };
Handle submit function should be setting the state inside the context provider

2020-09-21 07:30 UTC, emmyclef reviewed
ok, just slight modifications needed.

2020-09-25 05:21 UTC, emmyclef approved these changes

2020-09-25 05:33 UTC, HENRYKC24 approved these changes

2020-09-27 11:45 UTC, chibuike07 approved these changes

2020-09-28 01:11 UTC, closed without merging

2020-09-28 01:12 UTC, chibuike07 commented
This page has been approved